global using CommonBasicLibraries.CollectionClasses;
global using UpdateManager.CoreLibrary.Interfaces;
global using UpdateManager.CoreLibrary.PostBuildHelpers;
global using Microsoft.Extensions.DependencyInjection;
global using UpdateManager.CoreLibrary.DataAccess;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using UpdateManager.CoreLibrary.Models;
global using UpdateManager.CoreLibrary.Utilities;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using UpdateManager.CoreLibrary.ProjectFileHelpers;
global using UpdateManager.CoreLibrary.NugetHelpers;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
